name: simple_cubit_app
description: A simple Flutter application using the Cubit pattern for state management.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^0.2.0

flutter:
  uses-material-design: true